type User {
    id: ID
    firstName: String
    lastName: String
    email: String
    active: Boolean
}

input UserInput{
    firstName: String!
    lastName: String!
    email: String!
}

type Query {
    getUserById(id: ID!) : User!
    getAllUser:[User!]
}

type Mutation {
    createUser(input: UserInput) : User!
    updateUser(id: ID!, input: UserInput!) : User!
    deleteUser(id: ID!): Boolean
}